2019-08-10 17:24:12,053 INFO --------------------------------
2019-08-10 17:24:12,054 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 17:24:12,054 INFO --------------------------------
2019-08-10 17:24:12,054 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 17:24:14,456 INFO In startBooth()...
2019-08-10 17:24:19,331 INFO Calling CountdownText()...
2019-08-10 17:24:21,374 INFO Back from CountdownText()
2019-08-10 17:24:23,381 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 17:24:24,464 INFO In archiveImage()...
2019-08-10 17:24:24,465 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 17:24:24,466 INFO image_filename.ext: picture.jpg
2019-08-10 17:24:24,467 INFO next_idx: 25139148
2019-08-10 17:24:24,468 INFO new_filename: /home/pi/git/photobooth/images/picture_25139148.jpg
2019-08-10 17:24:24,541 INFO In archiveImage(): Exiting...
2019-08-10 17:24:24,585 INFO In displayImage():...
2019-08-10 17:24:24,830 INFO Exiting displayImage()
2019-08-10 17:24:24,831 INFO Upload to Picasa OFF in configuration
2019-08-10 17:24:24,831 INFO Uploading to Google Drive...
2019-08-10 17:24:24,832 INFO GoogleDriveUploader constructor: IN
2019-08-10 17:24:24,833 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 17:24:24,833 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 17:24:24,833 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 17:24:24,834 INFO Authenticator:__init__(): Found existing pickled file in [/home/pi/git/photobooth/secrets/]
2019-08-10 17:24:24,836 INFO Authenticator:__init__(): Loaded existing pickle file into object
2019-08-10 17:24:24,837 INFO Authenticator:__init__(): Returning!
2019-08-10 17:24:24,842 WARNING file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2019-08-10 17:24:24,843 INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
2019-08-10 17:24:25,057 INFO In BackgroundProcessor.kickOff()
2019-08-10 17:24:25,058 INFO GoogleDriveUploader.preWorkFunction()
2019-08-10 17:24:25,058 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 17:24:25,059 INFO In BackgroundProcessors.kickOff() - Exiting.
2019-08-10 17:24:25,059 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 17:24:25,059 INFO GoogleDriveUploader.workFunction()...
2019-08-10 17:24:25,130 INFO URL being requested: GET https://www.googleapis.com/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2C+files%28id%2C+name%29&alt=json&spaces=drive
2019-08-10 17:24:26,109 INFO GoogleDriveUploader.workFunction(): Uploading to folder: [NY-2018-2019], thefile: [/home/pi/git/photobooth/images/picture_25139148.jpg]...
2019-08-10 17:24:26,637 INFO URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart
2019-08-10 17:24:30,067 INFO Exiting startBooth()
2019-08-10 17:24:30,988 INFO GoogleDriveUploader.workFunction(): DONE with [/home/pi/git/photobooth/images/picture_25139148.jpg]
2019-08-10 17:24:30,990 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 17:24:30,991 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 17:24:31,462 INFO onClose(): Cleaning up uploaders...
2019-08-10 17:24:31,463 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 17:24:31,465 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 17:24:31,465 INFO Terminating thread...
2019-08-10 18:18:00,524 INFO --------------------------------
2019-08-10 18:18:00,525 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 18:18:00,525 INFO --------------------------------
2019-08-10 18:18:00,525 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 18:18:04,412 INFO In startBooth()...
2019-08-10 18:18:09,274 INFO Calling CountdownText()...
2019-08-10 18:18:11,298 INFO Back from CountdownText()
2019-08-10 18:18:13,306 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 18:18:14,254 INFO In archiveImage()...
2019-08-10 18:18:14,255 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 18:18:14,255 INFO image_filename.ext: picture.jpg
2019-08-10 18:18:14,256 INFO next_idx: 25142378
2019-08-10 18:18:14,256 INFO new_filename: /home/pi/git/photobooth/images/picture_25142378.jpg
2019-08-10 18:18:14,356 INFO In archiveImage(): Exiting...
2019-08-10 18:18:14,381 INFO In displayImage():...
2019-08-10 18:18:14,682 INFO Exiting displayImage()
2019-08-10 18:18:14,683 INFO Upload to Picasa OFF in configuration
2019-08-10 18:18:14,683 INFO Uploading to Google Drive...
2019-08-10 18:18:14,683 INFO GoogleDriveUploader constructor: IN
2019-08-10 18:18:14,684 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:18:14,684 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 18:18:14,685 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:18:14,685 ERROR !!EXCEPTION!! In startBooth()!
2019-08-10 18:18:14,686 ERROR -------------------------------------------------
2019-08-10 18:18:14,686 ERROR <type 'exceptions.Exception'>
2019-08-10 18:18:14,686 ERROR ('Authenticator: __init__(): Unable to find file: [client_secrets.json]',)
2019-08-10 18:18:14,687 ERROR Authenticator: __init__(): Unable to find file: [client_secrets.json]
2019-08-10 18:18:14,687 ERROR -------------------------------------------------
2019-08-10 18:18:14,688 ERROR [('/home/pi/git/photobooth/coregui/main.py', 182, 'startBooth', 'uploadImages(picsarray)'), ('/home/pi/git/photobooth/uploaders/upload.py', 31, 'uploadImages', 'drive_uploader = GoogleDriveUploader.instance()'), ('/home/pi/git/photobooth/uploaders/googledriveuploader.py', 31, 'instance', 'GoogleDriveUploader()'), ('/home/pi/git/photobooth/uploaders/googledriveuploader.py', 43, '__init__', 'self.auth = Authenticator("client_secrets.json", "saved_creds.pickle")'), ('/home/pi/git/photobooth/auth/auth.py', 39, '__init__', 'raise Exception ("Authenticator: __init__(): Unable to find file: [%s]"%client_secrets_filename)')]
2019-08-10 18:18:17,015 INFO onClose(): Cleaning up uploaders...
2019-08-10 18:23:17,993 INFO --------------------------------
2019-08-10 18:23:17,994 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 18:23:17,994 INFO --------------------------------
2019-08-10 18:23:17,994 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 18:23:20,411 INFO In startBooth()...
2019-08-10 18:23:25,289 INFO Calling CountdownText()...
2019-08-10 18:23:27,330 INFO Back from CountdownText()
2019-08-10 18:23:29,336 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 18:23:30,186 INFO In archiveImage()...
2019-08-10 18:23:30,187 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 18:23:30,187 INFO image_filename.ext: picture.jpg
2019-08-10 18:23:30,187 INFO next_idx: 25142694
2019-08-10 18:23:30,187 INFO new_filename: /home/pi/git/photobooth/images/picture_25142694.jpg
2019-08-10 18:23:30,216 INFO In archiveImage(): Exiting...
2019-08-10 18:23:30,235 INFO In displayImage():...
2019-08-10 18:23:30,478 INFO Exiting displayImage()
2019-08-10 18:23:30,479 INFO Upload to Picasa OFF in configuration
2019-08-10 18:23:30,487 INFO Uploading to Google Drive...
2019-08-10 18:23:30,488 INFO GoogleDriveUploader constructor: IN
2019-08-10 18:23:30,489 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:23:30,489 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 18:23:30,489 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:23:30,490 INFO Authenticator:__init__(): Found existing pickled file in [/home/pi/git/photobooth/secrets/]
2019-08-10 18:23:30,493 INFO Authenticator:__init__(): Loaded existing pickle file into object
2019-08-10 18:23:30,494 INFO Authenticator:__init__(): First time or pickled creds not valid
2019-08-10 18:23:30,494 INFO Authenticator:__init__(): Refreshing token
2019-08-10 18:23:30,937 INFO Authenticator:__init__(): Done refreshing token
2019-08-10 18:23:30,942 INFO Authenticator:__init__(): Dumped credentials into [/home/pi/git/photobooth/secrets/saved_creds.pickle]
2019-08-10 18:23:30,942 INFO Authenticator:__init__(): Returning!
2019-08-10 18:23:30,946 WARNING file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2019-08-10 18:23:30,947 INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
2019-08-10 18:23:31,188 INFO In BackgroundProcessor.kickOff()
2019-08-10 18:23:31,189 INFO GoogleDriveUploader.preWorkFunction()
2019-08-10 18:23:31,189 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:23:31,190 INFO In BackgroundProcessors.kickOff() - Exiting.
2019-08-10 18:23:31,190 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:23:31,190 INFO GoogleDriveUploader.workFunction()...
2019-08-10 18:23:31,259 INFO URL being requested: GET https://www.googleapis.com/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2C+files%28id%2C+name%29&alt=json&spaces=drive
2019-08-10 18:23:32,047 INFO GoogleDriveUploader.workFunction(): Uploading to folder: [NY-2018-2019], thefile: [/home/pi/git/photobooth/images/picture_25142694.jpg]...
2019-08-10 18:23:32,587 INFO URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart
2019-08-10 18:23:36,198 INFO Exiting startBooth()
2019-08-10 18:23:36,960 INFO GoogleDriveUploader.workFunction(): DONE with [/home/pi/git/photobooth/images/picture_25142694.jpg]
2019-08-10 18:23:36,960 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:23:36,960 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:23:39,663 INFO onClose(): Cleaning up uploaders...
2019-08-10 18:23:39,665 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:23:39,666 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:23:39,666 INFO Terminating thread...
2019-08-10 18:24:24,594 INFO --------------------------------
2019-08-10 18:24:24,594 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 18:24:24,594 INFO --------------------------------
2019-08-10 18:24:24,595 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 18:24:26,089 INFO In startBooth()...
2019-08-10 18:24:30,966 INFO Calling CountdownText()...
2019-08-10 18:24:33,007 INFO Back from CountdownText()
2019-08-10 18:24:35,017 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 18:24:35,961 INFO In archiveImage()...
2019-08-10 18:24:35,962 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 18:24:35,971 INFO image_filename.ext: picture.jpg
2019-08-10 18:24:35,972 INFO next_idx: 25142759
2019-08-10 18:24:35,973 INFO new_filename: /home/pi/git/photobooth/images/picture_25142759.jpg
2019-08-10 18:24:36,036 INFO In archiveImage(): Exiting...
2019-08-10 18:24:36,067 INFO In displayImage():...
2019-08-10 18:24:36,331 INFO Exiting displayImage()
2019-08-10 18:24:36,332 INFO Upload to Picasa OFF in configuration
2019-08-10 18:24:36,332 INFO Uploading to Google Drive...
2019-08-10 18:24:36,333 INFO GoogleDriveUploader constructor: IN
2019-08-10 18:24:36,334 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:24:36,334 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 18:24:36,334 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:24:36,335 INFO Authenticator:__init__(): Found existing pickled file in [/home/pi/git/photobooth/secrets/]
2019-08-10 18:24:36,337 INFO Authenticator:__init__(): Loaded existing pickle file into object
2019-08-10 18:24:36,338 INFO Authenticator:__init__(): Returning!
2019-08-10 18:24:36,343 WARNING file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2019-08-10 18:24:36,344 INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
2019-08-10 18:24:36,596 INFO In BackgroundProcessor.kickOff()
2019-08-10 18:24:36,598 INFO GoogleDriveUploader.preWorkFunction()
2019-08-10 18:24:36,599 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:24:36,599 INFO In BackgroundProcessors.kickOff() - Exiting.
2019-08-10 18:24:36,600 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:24:36,600 INFO GoogleDriveUploader.workFunction()...
2019-08-10 18:24:36,670 INFO URL being requested: GET https://www.googleapis.com/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2C+files%28id%2C+name%29&alt=json&spaces=drive
2019-08-10 18:24:37,241 INFO GoogleDriveUploader.workFunction(): Uploading to folder: [NY-2018-2019], thefile: [/home/pi/git/photobooth/images/picture_25142759.jpg]...
2019-08-10 18:24:37,784 INFO URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart
2019-08-10 18:24:41,608 INFO Exiting startBooth()
2019-08-10 18:24:42,136 INFO GoogleDriveUploader.workFunction(): DONE with [/home/pi/git/photobooth/images/picture_25142759.jpg]
2019-08-10 18:24:42,136 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:24:42,137 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:24:43,654 INFO onClose(): Cleaning up uploaders...
2019-08-10 18:24:43,655 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:24:43,656 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:24:43,657 INFO Terminating thread...
2019-08-10 18:26:52,699 INFO --------------------------------
2019-08-10 18:26:52,700 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 18:26:52,700 INFO --------------------------------
2019-08-10 18:26:52,700 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 18:26:54,150 INFO In startBooth()...
2019-08-10 18:26:59,022 INFO Calling CountdownText()...
2019-08-10 18:27:01,044 INFO Back from CountdownText()
2019-08-10 18:27:03,050 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 18:27:03,991 INFO In archiveImage()...
2019-08-10 18:27:03,992 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 18:27:03,993 INFO image_filename.ext: picture.jpg
2019-08-10 18:27:03,993 INFO next_idx: 25142907
2019-08-10 18:27:03,994 INFO new_filename: /home/pi/git/photobooth/images/picture_25142907.jpg
2019-08-10 18:27:04,069 INFO In archiveImage(): Exiting...
2019-08-10 18:27:04,114 INFO In displayImage():...
2019-08-10 18:27:04,421 INFO Exiting displayImage()
2019-08-10 18:27:04,422 INFO Upload to Picasa OFF in configuration
2019-08-10 18:27:04,422 INFO Uploading to Google Drive...
2019-08-10 18:27:04,422 INFO GoogleDriveUploader constructor: IN
2019-08-10 18:27:04,423 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:27:04,423 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 18:27:04,424 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:27:04,424 INFO Authenticator:__init__(): Found existing pickled file in [/home/pi/git/photobooth/secrets/]
2019-08-10 18:27:04,427 INFO Authenticator:__init__(): Loaded existing pickle file into object
2019-08-10 18:27:04,427 INFO Authenticator:__init__(): Returning!
2019-08-10 18:27:04,433 WARNING file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2019-08-10 18:27:04,434 INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
2019-08-10 18:27:04,635 INFO In BackgroundProcessor.kickOff()
2019-08-10 18:27:04,636 INFO GoogleDriveUploader.preWorkFunction()
2019-08-10 18:27:04,637 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:27:04,637 INFO In BackgroundProcessors.kickOff() - Exiting.
2019-08-10 18:27:04,638 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:27:04,638 INFO GoogleDriveUploader.workFunction()...
2019-08-10 18:27:04,705 INFO URL being requested: GET https://www.googleapis.com/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2C+files%28id%2C+name%29&alt=json&spaces=drive
2019-08-10 18:27:05,822 INFO GoogleDriveUploader.workFunction(): Uploading to folder: [NY-2018-2019], thefile: [/home/pi/git/photobooth/images/picture_25142907.jpg]...
2019-08-10 18:27:06,333 INFO URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart
2019-08-10 18:27:09,649 INFO Exiting startBooth()
2019-08-10 18:27:10,856 INFO onClose(): Cleaning up uploaders...
2019-08-10 18:27:10,870 INFO GoogleDriveUploader.workFunction(): DONE with [/home/pi/git/photobooth/images/picture_25142907.jpg]
2019-08-10 18:27:10,871 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:27:10,872 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:27:10,873 INFO Terminating thread...
2019-08-10 18:34:03,652 INFO --------------------------------
2019-08-10 18:34:03,653 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 18:34:03,653 INFO --------------------------------
2019-08-10 18:34:03,653 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 18:34:06,221 INFO In startBooth()...
2019-08-10 18:34:11,083 INFO Calling CountdownText()...
2019-08-10 18:34:13,126 INFO Back from CountdownText()
2019-08-10 18:34:15,133 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 18:34:15,869 INFO In archiveImage()...
2019-08-10 18:34:15,870 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 18:34:15,871 INFO image_filename.ext: picture.jpg
2019-08-10 18:34:15,871 INFO next_idx: 25143339
2019-08-10 18:34:15,872 INFO new_filename: /home/pi/git/photobooth/images/picture_25143339.jpg
2019-08-10 18:34:15,939 INFO In archiveImage(): Exiting...
2019-08-10 18:34:15,986 INFO In displayImage():...
2019-08-10 18:34:16,262 INFO Exiting displayImage()
2019-08-10 18:34:16,263 INFO Upload to Picasa OFF in configuration
2019-08-10 18:34:16,263 INFO Uploading to Google Drive...
2019-08-10 18:34:16,263 INFO GoogleDriveUploader constructor: IN
2019-08-10 18:34:16,264 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:34:16,265 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 18:34:16,265 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:34:16,266 ERROR !!EXCEPTION!! In startBooth()!
2019-08-10 18:34:16,266 ERROR -------------------------------------------------
2019-08-10 18:34:16,266 ERROR <type 'exceptions.Exception'>
2019-08-10 18:34:16,266 ERROR ('Authenticator: __init__(): Unable to find file: [client_secrets.json]',)
2019-08-10 18:34:16,267 ERROR Authenticator: __init__(): Unable to find file: [client_secrets.json]
2019-08-10 18:34:16,267 ERROR -------------------------------------------------
2019-08-10 18:34:16,268 ERROR [('/home/pi/git/photobooth/coregui/main.py', 182, 'startBooth', 'uploadImages(picsarray)'), ('/home/pi/git/photobooth/uploaders/upload.py', 31, 'uploadImages', 'drive_uploader = GoogleDriveUploader.instance()'), ('/home/pi/git/photobooth/uploaders/googledriveuploader.py', 31, 'instance', 'GoogleDriveUploader()'), ('/home/pi/git/photobooth/uploaders/googledriveuploader.py', 43, '__init__', 'self.auth = Authenticator("client_secrets.json", "saved_creds.pickle")'), ('/home/pi/git/photobooth/auth/auth.py', 39, '__init__', 'raise Exception ("Authenticator: __init__(): Unable to find file: [%s]"%client_secrets_filename)')]
2019-08-10 18:37:53,736 INFO --------------------------------
2019-08-10 18:37:53,737 INFO ------STARTING PHOTOBOOTH-------
2019-08-10 18:37:53,737 INFO --------------------------------
2019-08-10 18:37:53,737 INFO sys.path=[['/home/pi/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/home/pi/git/photobooth', '/home/pi/git/photobooth/scripts', '/home/pi/git/photobooth/coregui', '/home/pi/git/photobooth/corecam', '/home/pi/git/photobooth/uploaders', '/home/pi/git/photobooth/auth']]
2019-08-10 18:37:56,117 INFO In startBooth()...
2019-08-10 18:38:00,987 INFO Calling CountdownText()...
2019-08-10 18:38:03,027 INFO Back from CountdownText()
2019-08-10 18:38:05,033 INFO In BoothCamera.capture(): resolution= 3280x2464, ISO=200, sharpness=60
2019-08-10 18:38:05,971 INFO In archiveImage()...
2019-08-10 18:38:05,972 INFO archive_dir: /home/pi/git/photobooth/images
2019-08-10 18:38:05,972 INFO image_filename.ext: picture.jpg
2019-08-10 18:38:05,973 INFO next_idx: 25143569
2019-08-10 18:38:05,974 INFO new_filename: /home/pi/git/photobooth/images/picture_25143569.jpg
2019-08-10 18:38:06,042 INFO In archiveImage(): Exiting...
2019-08-10 18:38:06,075 INFO In displayImage():...
2019-08-10 18:38:06,387 INFO Exiting displayImage()
2019-08-10 18:38:06,388 INFO Upload to Picasa OFF in configuration
2019-08-10 18:38:06,388 INFO Uploading to Google Drive...
2019-08-10 18:38:06,388 INFO GoogleDriveUploader constructor: IN
2019-08-10 18:38:06,389 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:38:06,390 INFO Authenticator: __init__(): client_secrets=[client_secrets.json], pickle_filename=[saved_creds.pickle]
2019-08-10 18:38:06,390 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:38:06,391 INFO Authenticator:__init__(): Found existing pickled file in [/home/pi/git/photobooth/secrets/]
2019-08-10 18:38:06,393 INFO Authenticator:__init__(): Loaded existing pickle file into object
2019-08-10 18:38:06,393 INFO Authenticator:__init__(): Returning!
2019-08-10 18:38:06,398 WARNING file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2019-08-10 18:38:06,399 INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
2019-08-10 18:38:06,661 INFO In BackgroundProcessor.kickOff()
2019-08-10 18:38:06,662 INFO GoogleDriveUploader.preWorkFunction()
2019-08-10 18:38:06,663 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:38:06,663 INFO In BackgroundProcessors.kickOff() - Exiting.
2019-08-10 18:38:06,664 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:38:06,664 INFO GoogleDriveUploader.workFunction()...
2019-08-10 18:38:06,732 INFO URL being requested: GET https://www.googleapis.com/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2C+files%28id%2C+name%29&alt=json&spaces=drive
2019-08-10 18:38:07,277 INFO GoogleDriveUploader.workFunction(): Uploading to folder: [NY-2018-2019], thefile: [/home/pi/git/photobooth/images/picture_25143569.jpg]...
2019-08-10 18:38:07,798 INFO URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart
2019-08-10 18:38:11,672 INFO Exiting startBooth()
2019-08-10 18:38:12,983 INFO GoogleDriveUploader.workFunction(): DONE with [/home/pi/git/photobooth/images/picture_25143569.jpg]
2019-08-10 18:38:12,984 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [0]
2019-08-10 18:38:12,984 INFO BackgroundProcessor.run(): Nothing to upload; going to get some zzzzs
2019-08-10 18:38:14,709 INFO onClose(): Cleaning up uploaders...
2019-08-10 18:38:14,711 INFO BackgroundProcessor.enqueue(): Number of data sets in 'data_queue' = [1]
2019-08-10 18:38:14,712 INFO BackgroundProcessor.run(): Awake now. Number of data sets in 'data_queue' = [1]
2019-08-10 18:38:14,712 INFO Terminating thread...
